version: '3.9'
services:
  # MySQL server
  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: session
      MYSQL_DATABASE: session_db
      MYSQL_USER: session
      MYSQL_PASSWORD: session
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5